### ISSUE TITLE
First 3 values should be ints not floats.

### ISSUE THREAD

**Issue by spookycat** [isathar/Blender_UE4_VectorFieldEditor#12]
Hi There
There is a small error in the FGA file format, the first 3 values should be ints and not floats.
Chris

**Comment by isathar** [comment]
My notifications were a mess and I didn't see this until just now...

Thanks for letting me know, I'll update it as soon as I get a chance.

**Comment by isathar** [comment]
I finally got a round to fixing it. Thanks again!
