### ISSUE TITLE
Blender 2.80 update ?

### ISSUE THREAD

**Issue by motorsep** [isathar/Blender_UE4_VectorFieldEditor#13]
Is there any way you could update this add-on for Blender 2.80 ?

Thanks

**Comment by isathar** [comment]
I took a look at it last night and got most of it working in 2.8. I still need to figure out the new gpu module for drawing the velocity lines, and will upload it once I do.

There won't be any new features this time - just a quick port to the new API for now.

**Comment by isathar** [comment]
A quick progress update:
I got the velocity lines converted to the new gpu module (which added a nice performance boost to the editor, by the way). Sadly, there's still something going wrong with importing/exporting vector fields, so it'll be a little bit longer.

**Comment by isathar** [comment]
I just uploaded the update. I still need to update the way the physics templates are handled and set up the velocity lines to update automatically, but everything else should be working. 
The UI panel also needs a more convenient spot.
