### ISSUE TITLE
Changine LifeTime breaks Field

### ISSUE THREAD

**Issue by kaliber64** [isathar/Blender_UE4_VectorFieldEditor#14]
Blender Version 2.80.75
Changing the Lifetime of the Emitter results in particles only being emitted from the center of the particle system.
Default Value for Lifetime is 50. Simulation stops at 32.

**Comment by isathar** [comment]
Thanks for the report. It looks like the changes to a vector field's particle settings made by the script on creation don't appear in the particle system's settings menu and get reset if any settings are changed manually. I'm not sure what's causing this and will keep investigating.

**Comment by isathar** [comment]
I couldn't figure out what's going on with the particle system settings, but ended up adding a new setting to let you set a custom lifetime for particles (in the generate submenu). Editing any particle settings after creating a vector field will still reset everything.
I'm also adding figuring out what's going on with the particle settings to the to-do list for the next major update.

**Comment by kaliber64** [comment]
Sounds good thanks.
